# Use root/example as user/password credentials
version: '3.7'

services:
  mongo:
    image: mongo:4.2-rc-bionic
    restart: always
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
